title: Boxy is the best.
author: Boxy
email: boxy@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Wao this look awesome, and already I do nothing.

# social links
twitter_username: I don't have one
github_username:  Boxy

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
